/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AuthorizerType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Authorizer
 */
public class AuthorizerTest {
    private final Authorizer model = new Authorizer();

    /**
     * Model tests for Authorizer
     */
    @Test
    public void testAuthorizer() {
        // TODO: test Authorizer
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'providerARNs'
     */
    @Test
    public void providerARNsTest() {
        // TODO: test providerARNs
    }

    /**
     * Test the property 'authType'
     */
    @Test
    public void authTypeTest() {
        // TODO: test authType
    }

    /**
     * Test the property 'authorizerUri'
     */
    @Test
    public void authorizerUriTest() {
        // TODO: test authorizerUri
    }

    /**
     * Test the property 'authorizerCredentials'
     */
    @Test
    public void authorizerCredentialsTest() {
        // TODO: test authorizerCredentials
    }

    /**
     * Test the property 'identitySource'
     */
    @Test
    public void identitySourceTest() {
        // TODO: test identitySource
    }

    /**
     * Test the property 'identityValidationExpression'
     */
    @Test
    public void identityValidationExpressionTest() {
        // TODO: test identityValidationExpression
    }

    /**
     * Test the property 'authorizerResultTtlInSeconds'
     */
    @Test
    public void authorizerResultTtlInSecondsTest() {
        // TODO: test authorizerResultTtlInSeconds
    }

}
