/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.CreateDomainNameRequestEndpointConfiguration;
import org.openapitools.client.model.CreateDomainNameRequestMutualTlsAuthentication;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateDomainNameRequest
 */
public class CreateDomainNameRequestTest {
    private final CreateDomainNameRequest model = new CreateDomainNameRequest();

    /**
     * Model tests for CreateDomainNameRequest
     */
    @Test
    public void testCreateDomainNameRequest() {
        // TODO: test CreateDomainNameRequest
    }

    /**
     * Test the property 'domainName'
     */
    @Test
    public void domainNameTest() {
        // TODO: test domainName
    }

    /**
     * Test the property 'certificateName'
     */
    @Test
    public void certificateNameTest() {
        // TODO: test certificateName
    }

    /**
     * Test the property 'certificateBody'
     */
    @Test
    public void certificateBodyTest() {
        // TODO: test certificateBody
    }

    /**
     * Test the property 'certificatePrivateKey'
     */
    @Test
    public void certificatePrivateKeyTest() {
        // TODO: test certificatePrivateKey
    }

    /**
     * Test the property 'certificateChain'
     */
    @Test
    public void certificateChainTest() {
        // TODO: test certificateChain
    }

    /**
     * Test the property 'certificateArn'
     */
    @Test
    public void certificateArnTest() {
        // TODO: test certificateArn
    }

    /**
     * Test the property 'regionalCertificateName'
     */
    @Test
    public void regionalCertificateNameTest() {
        // TODO: test regionalCertificateName
    }

    /**
     * Test the property 'regionalCertificateArn'
     */
    @Test
    public void regionalCertificateArnTest() {
        // TODO: test regionalCertificateArn
    }

    /**
     * Test the property 'endpointConfiguration'
     */
    @Test
    public void endpointConfigurationTest() {
        // TODO: test endpointConfiguration
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'securityPolicy'
     */
    @Test
    public void securityPolicyTest() {
        // TODO: test securityPolicy
    }

    /**
     * Test the property 'mutualTlsAuthentication'
     */
    @Test
    public void mutualTlsAuthenticationTest() {
        // TODO: test mutualTlsAuthentication
    }

    /**
     * Test the property 'ownershipVerificationCertificateArn'
     */
    @Test
    public void ownershipVerificationCertificateArnTest() {
        // TODO: test ownershipVerificationCertificateArn
    }

}
