/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;
import org.openapitools.client.model.GatewayResponseType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GatewayResponse
 */
public class GatewayResponseTest {
    private final GatewayResponse model = new GatewayResponse();

    /**
     * Model tests for GatewayResponse
     */
    @Test
    public void testGatewayResponse() {
        // TODO: test GatewayResponse
    }

    /**
     * Test the property 'responseType'
     */
    @Test
    public void responseTypeTest() {
        // TODO: test responseType
    }

    /**
     * Test the property 'statusCode'
     */
    @Test
    public void statusCodeTest() {
        // TODO: test statusCode
    }

    /**
     * Test the property 'responseParameters'
     */
    @Test
    public void responseParametersTest() {
        // TODO: test responseParameters
    }

    /**
     * Test the property 'responseTemplates'
     */
    @Test
    public void responseTemplatesTest() {
        // TODO: test responseTemplates
    }

    /**
     * Test the property 'defaultResponse'
     */
    @Test
    public void defaultResponseTest() {
        // TODO: test defaultResponse
    }

}
