/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.UnauthorizedCacheControlHeaderStrategy;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MethodSetting
 */
public class MethodSettingTest {
    private final MethodSetting model = new MethodSetting();

    /**
     * Model tests for MethodSetting
     */
    @Test
    public void testMethodSetting() {
        // TODO: test MethodSetting
    }

    /**
     * Test the property 'metricsEnabled'
     */
    @Test
    public void metricsEnabledTest() {
        // TODO: test metricsEnabled
    }

    /**
     * Test the property 'loggingLevel'
     */
    @Test
    public void loggingLevelTest() {
        // TODO: test loggingLevel
    }

    /**
     * Test the property 'dataTraceEnabled'
     */
    @Test
    public void dataTraceEnabledTest() {
        // TODO: test dataTraceEnabled
    }

    /**
     * Test the property 'throttlingBurstLimit'
     */
    @Test
    public void throttlingBurstLimitTest() {
        // TODO: test throttlingBurstLimit
    }

    /**
     * Test the property 'throttlingRateLimit'
     */
    @Test
    public void throttlingRateLimitTest() {
        // TODO: test throttlingRateLimit
    }

    /**
     * Test the property 'cachingEnabled'
     */
    @Test
    public void cachingEnabledTest() {
        // TODO: test cachingEnabled
    }

    /**
     * Test the property 'cacheTtlInSeconds'
     */
    @Test
    public void cacheTtlInSecondsTest() {
        // TODO: test cacheTtlInSeconds
    }

    /**
     * Test the property 'cacheDataEncrypted'
     */
    @Test
    public void cacheDataEncryptedTest() {
        // TODO: test cacheDataEncrypted
    }

    /**
     * Test the property 'requireAuthorizationForCacheControl'
     */
    @Test
    public void requireAuthorizationForCacheControlTest() {
        // TODO: test requireAuthorizationForCacheControl
    }

    /**
     * Test the property 'unauthorizedCacheControlHeaderStrategy'
     */
    @Test
    public void unauthorizedCacheControlHeaderStrategyTest() {
        // TODO: test unauthorizedCacheControlHeaderStrategy
    }

}
