/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Map;
import org.openapitools.client.model.CacheClusterSize;
import org.openapitools.client.model.CacheClusterStatus;
import org.openapitools.client.model.StageAccessLogSettings;
import org.openapitools.client.model.StageCanarySettings;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Stage
 */
public class StageTest {
    private final Stage model = new Stage();

    /**
     * Model tests for Stage
     */
    @Test
    public void testStage() {
        // TODO: test Stage
    }

    /**
     * Test the property 'deploymentId'
     */
    @Test
    public void deploymentIdTest() {
        // TODO: test deploymentId
    }

    /**
     * Test the property 'clientCertificateId'
     */
    @Test
    public void clientCertificateIdTest() {
        // TODO: test clientCertificateId
    }

    /**
     * Test the property 'stageName'
     */
    @Test
    public void stageNameTest() {
        // TODO: test stageName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'cacheClusterEnabled'
     */
    @Test
    public void cacheClusterEnabledTest() {
        // TODO: test cacheClusterEnabled
    }

    /**
     * Test the property 'cacheClusterSize'
     */
    @Test
    public void cacheClusterSizeTest() {
        // TODO: test cacheClusterSize
    }

    /**
     * Test the property 'cacheClusterStatus'
     */
    @Test
    public void cacheClusterStatusTest() {
        // TODO: test cacheClusterStatus
    }

    /**
     * Test the property 'methodSettings'
     */
    @Test
    public void methodSettingsTest() {
        // TODO: test methodSettings
    }

    /**
     * Test the property 'variables'
     */
    @Test
    public void variablesTest() {
        // TODO: test variables
    }

    /**
     * Test the property 'documentationVersion'
     */
    @Test
    public void documentationVersionTest() {
        // TODO: test documentationVersion
    }

    /**
     * Test the property 'accessLogSettings'
     */
    @Test
    public void accessLogSettingsTest() {
        // TODO: test accessLogSettings
    }

    /**
     * Test the property 'canarySettings'
     */
    @Test
    public void canarySettingsTest() {
        // TODO: test canarySettings
    }

    /**
     * Test the property 'tracingEnabled'
     */
    @Test
    public void tracingEnabledTest() {
        // TODO: test tracingEnabled
    }

    /**
     * Test the property 'webAclArn'
     */
    @Test
    public void webAclArnTest() {
        // TODO: test webAclArn
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'lastUpdatedDate'
     */
    @Test
    public void lastUpdatedDateTest() {
        // TODO: test lastUpdatedDate
    }

}
