/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StageCanarySettings
 */
public class StageCanarySettingsTest {
    private final StageCanarySettings model = new StageCanarySettings();

    /**
     * Model tests for StageCanarySettings
     */
    @Test
    public void testStageCanarySettings() {
        // TODO: test StageCanarySettings
    }

    /**
     * Test the property 'percentTraffic'
     */
    @Test
    public void percentTrafficTest() {
        // TODO: test percentTraffic
    }

    /**
     * Test the property 'deploymentId'
     */
    @Test
    public void deploymentIdTest() {
        // TODO: test deploymentId
    }

    /**
     * Test the property 'stageVariableOverrides'
     */
    @Test
    public void stageVariableOverridesTest() {
        // TODO: test stageVariableOverrides
    }

    /**
     * Test the property 'useStageCache'
     */
    @Test
    public void useStageCacheTest() {
        // TODO: test useStageCache
    }

}
