/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TestInvokeAuthorizerResponse
 */
public class TestInvokeAuthorizerResponseTest {
    private final TestInvokeAuthorizerResponse model = new TestInvokeAuthorizerResponse();

    /**
     * Model tests for TestInvokeAuthorizerResponse
     */
    @Test
    public void testTestInvokeAuthorizerResponse() {
        // TODO: test TestInvokeAuthorizerResponse
    }

    /**
     * Test the property 'clientStatus'
     */
    @Test
    public void clientStatusTest() {
        // TODO: test clientStatus
    }

    /**
     * Test the property 'log'
     */
    @Test
    public void logTest() {
        // TODO: test log
    }

    /**
     * Test the property 'latency'
     */
    @Test
    public void latencyTest() {
        // TODO: test latency
    }

    /**
     * Test the property 'principalId'
     */
    @Test
    public void principalIdTest() {
        // TODO: test principalId
    }

    /**
     * Test the property 'policy'
     */
    @Test
    public void policyTest() {
        // TODO: test policy
    }

    /**
     * Test the property 'authorization'
     */
    @Test
    public void authorizationTest() {
        // TODO: test authorization
    }

    /**
     * Test the property 'claims'
     */
    @Test
    public void claimsTest() {
        // TODO: test claims
    }

}
