package main

import (
	"github.com/amazon-api-gateway/mcp-server/config"
	"github.com/amazon-api-gateway/mcp-server/models"
	tools_restapis "github.com/amazon-api-gateway/mcp-server/tools/restapis"
	tools_tags "github.com/amazon-api-gateway/mcp-server/tools/tags"
	tools_sdktypes "github.com/amazon-api-gateway/mcp-server/tools/sdktypes"
	tools_usageplans "github.com/amazon-api-gateway/mcp-server/tools/usageplans"
	tools_vpclinks "github.com/amazon-api-gateway/mcp-server/tools/vpclinks"
	tools_account "github.com/amazon-api-gateway/mcp-server/tools/account"
	tools_apikeys "github.com/amazon-api-gateway/mcp-server/tools/apikeys"
	tools_domainnames "github.com/amazon-api-gateway/mcp-server/tools/domainnames"
	tools_restapis_mode_import "github.com/amazon-api-gateway/mcp-server/tools/restapis_mode_import"
	tools_clientcertificates "github.com/amazon-api-gateway/mcp-server/tools/clientcertificates"
	tools_apikeys_mode_import_format "github.com/amazon-api-gateway/mcp-server/tools/apikeys_mode_import_format"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_restapis.CreateDeletemethodTool(cfg),
		tools_restapis.CreateGetmethodTool(cfg),
		tools_restapis.CreateUpdatemethodTool(cfg),
		tools_restapis.CreateTestinvokemethodTool(cfg),
		tools_restapis.CreatePutmethodTool(cfg),
		tools_tags.CreateGettagsTool(cfg),
		tools_tags.CreateTagresourceTool(cfg),
		tools_restapis.CreateFlushstagecacheTool(cfg),
		tools_sdktypes.CreateGetsdktypesTool(cfg),
		tools_restapis.CreateGetmodelsTool(cfg),
		tools_restapis.CreateCreatemodelTool(cfg),
		tools_usageplans.CreateDeleteusageplanTool(cfg),
		tools_usageplans.CreateGetusageplanTool(cfg),
		tools_usageplans.CreateUpdateusageplanTool(cfg),
		tools_vpclinks.CreateGetvpclinksTool(cfg),
		tools_vpclinks.CreateCreatevpclinkTool(cfg),
		tools_restapis.CreateGetexportTool(cfg),
		tools_restapis.CreateDeleterestapiTool(cfg),
		tools_restapis.CreateGetrestapiTool(cfg),
		tools_restapis.CreateUpdaterestapiTool(cfg),
		tools_restapis.CreatePutrestapiTool(cfg),
		tools_restapis.CreateDeletedocumentationversionTool(cfg),
		tools_restapis.CreateGetdocumentationversionTool(cfg),
		tools_restapis.CreateUpdatedocumentationversionTool(cfg),
		tools_restapis.CreateDeleterequestvalidatorTool(cfg),
		tools_restapis.CreateGetrequestvalidatorTool(cfg),
		tools_restapis.CreateUpdaterequestvalidatorTool(cfg),
		tools_usageplans.CreateUpdateusageTool(cfg),
		tools_usageplans.CreateGetusageplankeysTool(cfg),
		tools_usageplans.CreateCreateusageplankeyTool(cfg),
		tools_restapis.CreateImportdocumentationpartsTool(cfg),
		tools_restapis.CreateGetdocumentationpartsTool(cfg),
		tools_restapis.CreateCreatedocumentationpartTool(cfg),
		tools_restapis.CreateGetdocumentationversionsTool(cfg),
		tools_restapis.CreateCreatedocumentationversionTool(cfg),
		tools_restapis.CreateDeletemodelTool(cfg),
		tools_restapis.CreateGetmodelTool(cfg),
		tools_restapis.CreateUpdatemodelTool(cfg),
		tools_usageplans.CreateCreateusageplanTool(cfg),
		tools_usageplans.CreateGetusageplansTool(cfg),
		tools_account.CreateGetaccountTool(cfg),
		tools_account.CreateUpdateaccountTool(cfg),
		tools_restapis.CreateDeletestageTool(cfg),
		tools_restapis.CreateGetstageTool(cfg),
		tools_restapis.CreateUpdatestageTool(cfg),
		tools_sdktypes.CreateGetsdktypeTool(cfg),
		tools_apikeys.CreateDeleteapikeyTool(cfg),
		tools_apikeys.CreateGetapikeyTool(cfg),
		tools_apikeys.CreateUpdateapikeyTool(cfg),
		tools_restapis.CreateDeletemethodresponseTool(cfg),
		tools_restapis.CreateGetmethodresponseTool(cfg),
		tools_restapis.CreateUpdatemethodresponseTool(cfg),
		tools_restapis.CreatePutmethodresponseTool(cfg),
		tools_restapis.CreateGetstagesTool(cfg),
		tools_restapis.CreateCreatestageTool(cfg),
		tools_restapis.CreateDeletedeploymentTool(cfg),
		tools_restapis.CreateGetdeploymentTool(cfg),
		tools_restapis.CreateUpdatedeploymentTool(cfg),
		tools_restapis.CreateGetdocumentationpartTool(cfg),
		tools_restapis.CreateUpdatedocumentationpartTool(cfg),
		tools_restapis.CreateDeletedocumentationpartTool(cfg),
		tools_restapis.CreateGetresourcesTool(cfg),
		tools_domainnames.CreateDeletebasepathmappingTool(cfg),
		tools_domainnames.CreateGetbasepathmappingTool(cfg),
		tools_domainnames.CreateUpdatebasepathmappingTool(cfg),
		tools_restapis.CreateDeleteintegrationTool(cfg),
		tools_restapis.CreateGetintegrationTool(cfg),
		tools_restapis.CreateUpdateintegrationTool(cfg),
		tools_restapis.CreatePutintegrationTool(cfg),
		tools_apikeys.CreateGetapikeysTool(cfg),
		tools_apikeys.CreateCreateapikeyTool(cfg),
		tools_restapis.CreateGetresourceTool(cfg),
		tools_restapis.CreateUpdateresourceTool(cfg),
		tools_restapis.CreateDeleteresourceTool(cfg),
		tools_restapis_mode_import.CreateImportrestapiTool(cfg),
		tools_restapis.CreateCreatedeploymentTool(cfg),
		tools_restapis.CreateGetdeploymentsTool(cfg),
		tools_usageplans.CreateGetusageTool(cfg),
		tools_restapis.CreateFlushstageauthorizerscacheTool(cfg),
		tools_clientcertificates.CreateDeleteclientcertificateTool(cfg),
		tools_clientcertificates.CreateGetclientcertificateTool(cfg),
		tools_clientcertificates.CreateUpdateclientcertificateTool(cfg),
		tools_domainnames.CreateGetbasepathmappingsTool(cfg),
		tools_domainnames.CreateCreatebasepathmappingTool(cfg),
		tools_restapis.CreateGetgatewayresponsesTool(cfg),
		tools_clientcertificates.CreateGetclientcertificatesTool(cfg),
		tools_clientcertificates.CreateGenerateclientcertificateTool(cfg),
		tools_domainnames.CreateGetdomainnamesTool(cfg),
		tools_domainnames.CreateCreatedomainnameTool(cfg),
		tools_restapis.CreateGetmodeltemplateTool(cfg),
		tools_restapis.CreateDeleteintegrationresponseTool(cfg),
		tools_restapis.CreateGetintegrationresponseTool(cfg),
		tools_restapis.CreateUpdateintegrationresponseTool(cfg),
		tools_restapis.CreatePutintegrationresponseTool(cfg),
		tools_restapis.CreateGetauthorizersTool(cfg),
		tools_restapis.CreateCreateauthorizerTool(cfg),
		tools_vpclinks.CreateDeletevpclinkTool(cfg),
		tools_vpclinks.CreateGetvpclinkTool(cfg),
		tools_vpclinks.CreateUpdatevpclinkTool(cfg),
		tools_restapis.CreateUpdategatewayresponseTool(cfg),
		tools_restapis.CreatePutgatewayresponseTool(cfg),
		tools_restapis.CreateDeletegatewayresponseTool(cfg),
		tools_restapis.CreateGetgatewayresponseTool(cfg),
		tools_restapis.CreateGetrequestvalidatorsTool(cfg),
		tools_restapis.CreateCreaterequestvalidatorTool(cfg),
		tools_restapis.CreateDeleteauthorizerTool(cfg),
		tools_restapis.CreateGetauthorizerTool(cfg),
		tools_restapis.CreateUpdateauthorizerTool(cfg),
		tools_restapis.CreateTestinvokeauthorizerTool(cfg),
		tools_restapis.CreateGetsdkTool(cfg),
		tools_restapis.CreateCreateresourceTool(cfg),
		tools_tags.CreateUntagresourceTool(cfg),
		tools_usageplans.CreateDeleteusageplankeyTool(cfg),
		tools_usageplans.CreateGetusageplankeyTool(cfg),
		tools_apikeys_mode_import_format.CreateImportapikeysTool(cfg),
		tools_domainnames.CreateDeletedomainnameTool(cfg),
		tools_domainnames.CreateGetdomainnameTool(cfg),
		tools_domainnames.CreateUpdatedomainnameTool(cfg),
		tools_restapis.CreateGetrestapisTool(cfg),
		tools_restapis.CreateCreaterestapiTool(cfg),
	}
}
