/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Returns the status of the CacheCluster.
 */
@JsonAdapter(CacheClusterStatus.Adapter.class)
public enum CacheClusterStatus {
  
  CREATE_IN_PROGRESS("CREATE_IN_PROGRESS"),
  
  AVAILABLE("AVAILABLE"),
  
  DELETE_IN_PROGRESS("DELETE_IN_PROGRESS"),
  
  NOT_AVAILABLE("NOT_AVAILABLE"),
  
  FLUSH_IN_PROGRESS("FLUSH_IN_PROGRESS");

  private String value;

  CacheClusterStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CacheClusterStatus fromValue(String value) {
    for (CacheClusterStatus b : CacheClusterStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CacheClusterStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final CacheClusterStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CacheClusterStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CacheClusterStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    CacheClusterStatus.fromValue(value);
  }
}

