/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateBasePathMappingRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:10:54.869209+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateBasePathMappingRequest {
  public static final String SERIALIZED_NAME_BASE_PATH = "basePath";
  @SerializedName(SERIALIZED_NAME_BASE_PATH)
  @javax.annotation.Nullable
  private String basePath;

  public static final String SERIALIZED_NAME_REST_API_ID = "restApiId";
  @SerializedName(SERIALIZED_NAME_REST_API_ID)
  @javax.annotation.Nonnull
  private String restApiId;

  public static final String SERIALIZED_NAME_STAGE = "stage";
  @SerializedName(SERIALIZED_NAME_STAGE)
  @javax.annotation.Nullable
  private String stage;

  public CreateBasePathMappingRequest() {
  }

  public CreateBasePathMappingRequest basePath(@javax.annotation.Nullable String basePath) {
    this.basePath = basePath;
    return this;
  }

  /**
   * The base path name that callers of the API must provide as part of the URL after the domain name. This value must be unique for all of the mappings across a single API. Specify &#39;(none)&#39; if you do not want callers to specify a base path name after the domain name.
   * @return basePath
   */
  @javax.annotation.Nullable
  public String getBasePath() {
    return basePath;
  }

  public void setBasePath(@javax.annotation.Nullable String basePath) {
    this.basePath = basePath;
  }


  public CreateBasePathMappingRequest restApiId(@javax.annotation.Nonnull String restApiId) {
    this.restApiId = restApiId;
    return this;
  }

  /**
   * The string identifier of the associated RestApi.
   * @return restApiId
   */
  @javax.annotation.Nonnull
  public String getRestApiId() {
    return restApiId;
  }

  public void setRestApiId(@javax.annotation.Nonnull String restApiId) {
    this.restApiId = restApiId;
  }


  public CreateBasePathMappingRequest stage(@javax.annotation.Nullable String stage) {
    this.stage = stage;
    return this;
  }

  /**
   * The name of the API&#39;s stage that you want to use for this mapping. Specify &#39;(none)&#39; if you want callers to explicitly specify the stage name after any base path name.
   * @return stage
   */
  @javax.annotation.Nullable
  public String getStage() {
    return stage;
  }

  public void setStage(@javax.annotation.Nullable String stage) {
    this.stage = stage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBasePathMappingRequest createBasePathMappingRequest = (CreateBasePathMappingRequest) o;
    return Objects.equals(this.basePath, createBasePathMappingRequest.basePath) &&
        Objects.equals(this.restApiId, createBasePathMappingRequest.restApiId) &&
        Objects.equals(this.stage, createBasePathMappingRequest.stage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(basePath, restApiId, stage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBasePathMappingRequest {\n");
    sb.append("    basePath: ").append(toIndentedString(basePath)).append("\n");
    sb.append("    restApiId: ").append(toIndentedString(restApiId)).append("\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("basePath");
    openapiFields.add("restApiId");
    openapiFields.add("stage");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("restApiId");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateBasePathMappingRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateBasePathMappingRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateBasePathMappingRequest is not found in the empty JSON string", CreateBasePathMappingRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateBasePathMappingRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateBasePathMappingRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateBasePathMappingRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("basePath") != null && !jsonObj.get("basePath").isJsonNull()) && !jsonObj.get("basePath").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `basePath` to be a primitive type in the JSON string but got `%s`", jsonObj.get("basePath").toString()));
      }
      if (!jsonObj.get("restApiId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `restApiId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("restApiId").toString()));
      }
      if ((jsonObj.get("stage") != null && !jsonObj.get("stage").isJsonNull()) && !jsonObj.get("stage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stage").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateBasePathMappingRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateBasePathMappingRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateBasePathMappingRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateBasePathMappingRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateBasePathMappingRequest>() {
           @Override
           public void write(JsonWriter out, CreateBasePathMappingRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateBasePathMappingRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateBasePathMappingRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateBasePathMappingRequest
   * @throws IOException if the JSON string is invalid with respect to CreateBasePathMappingRequest
   */
  public static CreateBasePathMappingRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateBasePathMappingRequest.class);
  }

  /**
   * Convert an instance of CreateBasePathMappingRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

