/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets DomainNameStatus
 */
@JsonAdapter(DomainNameStatus.Adapter.class)
public enum DomainNameStatus {
  
  AVAILABLE("AVAILABLE"),
  
  UPDATING("UPDATING"),
  
  PENDING("PENDING"),
  
  PENDING_CERTIFICATE_REIMPORT("PENDING_CERTIFICATE_REIMPORT"),
  
  PENDING_OWNERSHIP_VERIFICATION("PENDING_OWNERSHIP_VERIFICATION");

  private String value;

  DomainNameStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DomainNameStatus fromValue(String value) {
    for (DomainNameStatus b : DomainNameStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DomainNameStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final DomainNameStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DomainNameStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DomainNameStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    DomainNameStatus.fromValue(value);
  }
}

