/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * The endpoint configuration to indicate the types of endpoints an API (RestApi) or its custom domain name (DomainName) has. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:10:54.869209+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class EndpointConfiguration {
  public static final String SERIALIZED_NAME_TYPES = "types";
  @SerializedName(SERIALIZED_NAME_TYPES)
  @javax.annotation.Nullable
  private List types;

  public static final String SERIALIZED_NAME_VPC_ENDPOINT_IDS = "vpcEndpointIds";
  @SerializedName(SERIALIZED_NAME_VPC_ENDPOINT_IDS)
  @javax.annotation.Nullable
  private List vpcEndpointIds;

  public EndpointConfiguration() {
  }

  public EndpointConfiguration types(@javax.annotation.Nullable List types) {
    this.types = types;
    return this;
  }

  /**
   * Get types
   * @return types
   */
  @javax.annotation.Nullable
  public List getTypes() {
    return types;
  }

  public void setTypes(@javax.annotation.Nullable List types) {
    this.types = types;
  }


  public EndpointConfiguration vpcEndpointIds(@javax.annotation.Nullable List vpcEndpointIds) {
    this.vpcEndpointIds = vpcEndpointIds;
    return this;
  }

  /**
   * Get vpcEndpointIds
   * @return vpcEndpointIds
   */
  @javax.annotation.Nullable
  public List getVpcEndpointIds() {
    return vpcEndpointIds;
  }

  public void setVpcEndpointIds(@javax.annotation.Nullable List vpcEndpointIds) {
    this.vpcEndpointIds = vpcEndpointIds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EndpointConfiguration endpointConfiguration = (EndpointConfiguration) o;
    return Objects.equals(this.types, endpointConfiguration.types) &&
        Objects.equals(this.vpcEndpointIds, endpointConfiguration.vpcEndpointIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(types, vpcEndpointIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EndpointConfiguration {\n");
    sb.append("    types: ").append(toIndentedString(types)).append("\n");
    sb.append("    vpcEndpointIds: ").append(toIndentedString(vpcEndpointIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("types");
    openapiFields.add("vpcEndpointIds");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EndpointConfiguration
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EndpointConfiguration.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EndpointConfiguration is not found in the empty JSON string", EndpointConfiguration.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EndpointConfiguration.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EndpointConfiguration` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `types`
      if (jsonObj.get("types") != null && !jsonObj.get("types").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("types"));
      }
      // validate the optional field `vpcEndpointIds`
      if (jsonObj.get("vpcEndpointIds") != null && !jsonObj.get("vpcEndpointIds").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("vpcEndpointIds"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EndpointConfiguration.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EndpointConfiguration' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EndpointConfiguration> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EndpointConfiguration.class));

       return (TypeAdapter<T>) new TypeAdapter<EndpointConfiguration>() {
           @Override
           public void write(JsonWriter out, EndpointConfiguration value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EndpointConfiguration read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EndpointConfiguration given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EndpointConfiguration
   * @throws IOException if the JSON string is invalid with respect to EndpointConfiguration
   */
  public static EndpointConfiguration fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EndpointConfiguration.class);
  }

  /**
   * Convert an instance of EndpointConfiguration to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

