/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;
import org.openapitools.client.model.ContentHandlingStrategy;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Represents an integration response. The status code must map to an existing MethodResponse, and parameters and templates can be used to transform the back-end response.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:10:54.869209+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class IntegrationResponse {
  public static final String SERIALIZED_NAME_STATUS_CODE = "statusCode";
  @SerializedName(SERIALIZED_NAME_STATUS_CODE)
  @javax.annotation.Nullable
  private String statusCode;

  public static final String SERIALIZED_NAME_SELECTION_PATTERN = "selectionPattern";
  @SerializedName(SERIALIZED_NAME_SELECTION_PATTERN)
  @javax.annotation.Nullable
  private String selectionPattern;

  public static final String SERIALIZED_NAME_RESPONSE_PARAMETERS = "responseParameters";
  @SerializedName(SERIALIZED_NAME_RESPONSE_PARAMETERS)
  @javax.annotation.Nullable
  private Map responseParameters;

  public static final String SERIALIZED_NAME_RESPONSE_TEMPLATES = "responseTemplates";
  @SerializedName(SERIALIZED_NAME_RESPONSE_TEMPLATES)
  @javax.annotation.Nullable
  private Map responseTemplates;

  public static final String SERIALIZED_NAME_CONTENT_HANDLING = "contentHandling";
  @SerializedName(SERIALIZED_NAME_CONTENT_HANDLING)
  @javax.annotation.Nullable
  private ContentHandlingStrategy contentHandling;

  public IntegrationResponse() {
  }

  public IntegrationResponse statusCode(@javax.annotation.Nullable String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

  /**
   * Get statusCode
   * @return statusCode
   */
  @javax.annotation.Nullable
  public String getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(@javax.annotation.Nullable String statusCode) {
    this.statusCode = statusCode;
  }


  public IntegrationResponse selectionPattern(@javax.annotation.Nullable String selectionPattern) {
    this.selectionPattern = selectionPattern;
    return this;
  }

  /**
   * Get selectionPattern
   * @return selectionPattern
   */
  @javax.annotation.Nullable
  public String getSelectionPattern() {
    return selectionPattern;
  }

  public void setSelectionPattern(@javax.annotation.Nullable String selectionPattern) {
    this.selectionPattern = selectionPattern;
  }


  public IntegrationResponse responseParameters(@javax.annotation.Nullable Map responseParameters) {
    this.responseParameters = responseParameters;
    return this;
  }

  /**
   * Get responseParameters
   * @return responseParameters
   */
  @javax.annotation.Nullable
  public Map getResponseParameters() {
    return responseParameters;
  }

  public void setResponseParameters(@javax.annotation.Nullable Map responseParameters) {
    this.responseParameters = responseParameters;
  }


  public IntegrationResponse responseTemplates(@javax.annotation.Nullable Map responseTemplates) {
    this.responseTemplates = responseTemplates;
    return this;
  }

  /**
   * Get responseTemplates
   * @return responseTemplates
   */
  @javax.annotation.Nullable
  public Map getResponseTemplates() {
    return responseTemplates;
  }

  public void setResponseTemplates(@javax.annotation.Nullable Map responseTemplates) {
    this.responseTemplates = responseTemplates;
  }


  public IntegrationResponse contentHandling(@javax.annotation.Nullable ContentHandlingStrategy contentHandling) {
    this.contentHandling = contentHandling;
    return this;
  }

  /**
   * Get contentHandling
   * @return contentHandling
   */
  @javax.annotation.Nullable
  public ContentHandlingStrategy getContentHandling() {
    return contentHandling;
  }

  public void setContentHandling(@javax.annotation.Nullable ContentHandlingStrategy contentHandling) {
    this.contentHandling = contentHandling;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationResponse integrationResponse = (IntegrationResponse) o;
    return Objects.equals(this.statusCode, integrationResponse.statusCode) &&
        Objects.equals(this.selectionPattern, integrationResponse.selectionPattern) &&
        Objects.equals(this.responseParameters, integrationResponse.responseParameters) &&
        Objects.equals(this.responseTemplates, integrationResponse.responseTemplates) &&
        Objects.equals(this.contentHandling, integrationResponse.contentHandling);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statusCode, selectionPattern, responseParameters, responseTemplates, contentHandling);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationResponse {\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    selectionPattern: ").append(toIndentedString(selectionPattern)).append("\n");
    sb.append("    responseParameters: ").append(toIndentedString(responseParameters)).append("\n");
    sb.append("    responseTemplates: ").append(toIndentedString(responseTemplates)).append("\n");
    sb.append("    contentHandling: ").append(toIndentedString(contentHandling)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("statusCode");
    openapiFields.add("selectionPattern");
    openapiFields.add("responseParameters");
    openapiFields.add("responseTemplates");
    openapiFields.add("contentHandling");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IntegrationResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IntegrationResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IntegrationResponse is not found in the empty JSON string", IntegrationResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IntegrationResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `IntegrationResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `statusCode`
      if (jsonObj.get("statusCode") != null && !jsonObj.get("statusCode").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("statusCode"));
      }
      // validate the optional field `selectionPattern`
      if (jsonObj.get("selectionPattern") != null && !jsonObj.get("selectionPattern").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("selectionPattern"));
      }
      // validate the optional field `responseParameters`
      if (jsonObj.get("responseParameters") != null && !jsonObj.get("responseParameters").isJsonNull()) {
        Map.validateJsonElement(jsonObj.get("responseParameters"));
      }
      // validate the optional field `responseTemplates`
      if (jsonObj.get("responseTemplates") != null && !jsonObj.get("responseTemplates").isJsonNull()) {
        Map.validateJsonElement(jsonObj.get("responseTemplates"));
      }
      // validate the optional field `contentHandling`
      if (jsonObj.get("contentHandling") != null && !jsonObj.get("contentHandling").isJsonNull()) {
        ContentHandlingStrategy.validateJsonElement(jsonObj.get("contentHandling"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IntegrationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IntegrationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IntegrationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IntegrationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<IntegrationResponse>() {
           @Override
           public void write(JsonWriter out, IntegrationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IntegrationResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IntegrationResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IntegrationResponse
   * @throws IOException if the JSON string is invalid with respect to IntegrationResponse
   */
  public static IntegrationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IntegrationResponse.class);
  }

  /**
   * Convert an instance of IntegrationResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

