/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Represents a method response of a given HTTP status code returned to the client. The method response is passed from the back end through the associated integration response that can be transformed using a mapping template. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:10:54.869209+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class MethodResponse {
  public static final String SERIALIZED_NAME_STATUS_CODE = "statusCode";
  @SerializedName(SERIALIZED_NAME_STATUS_CODE)
  @javax.annotation.Nullable
  private String statusCode;

  public static final String SERIALIZED_NAME_RESPONSE_PARAMETERS = "responseParameters";
  @SerializedName(SERIALIZED_NAME_RESPONSE_PARAMETERS)
  @javax.annotation.Nullable
  private Map responseParameters;

  public static final String SERIALIZED_NAME_RESPONSE_MODELS = "responseModels";
  @SerializedName(SERIALIZED_NAME_RESPONSE_MODELS)
  @javax.annotation.Nullable
  private Map responseModels;

  public MethodResponse() {
  }

  public MethodResponse statusCode(@javax.annotation.Nullable String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

  /**
   * Get statusCode
   * @return statusCode
   */
  @javax.annotation.Nullable
  public String getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(@javax.annotation.Nullable String statusCode) {
    this.statusCode = statusCode;
  }


  public MethodResponse responseParameters(@javax.annotation.Nullable Map responseParameters) {
    this.responseParameters = responseParameters;
    return this;
  }

  /**
   * Get responseParameters
   * @return responseParameters
   */
  @javax.annotation.Nullable
  public Map getResponseParameters() {
    return responseParameters;
  }

  public void setResponseParameters(@javax.annotation.Nullable Map responseParameters) {
    this.responseParameters = responseParameters;
  }


  public MethodResponse responseModels(@javax.annotation.Nullable Map responseModels) {
    this.responseModels = responseModels;
    return this;
  }

  /**
   * Get responseModels
   * @return responseModels
   */
  @javax.annotation.Nullable
  public Map getResponseModels() {
    return responseModels;
  }

  public void setResponseModels(@javax.annotation.Nullable Map responseModels) {
    this.responseModels = responseModels;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MethodResponse methodResponse = (MethodResponse) o;
    return Objects.equals(this.statusCode, methodResponse.statusCode) &&
        Objects.equals(this.responseParameters, methodResponse.responseParameters) &&
        Objects.equals(this.responseModels, methodResponse.responseModels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statusCode, responseParameters, responseModels);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MethodResponse {\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    responseParameters: ").append(toIndentedString(responseParameters)).append("\n");
    sb.append("    responseModels: ").append(toIndentedString(responseModels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("statusCode");
    openapiFields.add("responseParameters");
    openapiFields.add("responseModels");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MethodResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MethodResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MethodResponse is not found in the empty JSON string", MethodResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MethodResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MethodResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `statusCode`
      if (jsonObj.get("statusCode") != null && !jsonObj.get("statusCode").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("statusCode"));
      }
      // validate the optional field `responseParameters`
      if (jsonObj.get("responseParameters") != null && !jsonObj.get("responseParameters").isJsonNull()) {
        Map.validateJsonElement(jsonObj.get("responseParameters"));
      }
      // validate the optional field `responseModels`
      if (jsonObj.get("responseModels") != null && !jsonObj.get("responseModels").isJsonNull()) {
        Map.validateJsonElement(jsonObj.get("responseModels"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MethodResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MethodResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MethodResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MethodResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<MethodResponse>() {
           @Override
           public void write(JsonWriter out, MethodResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MethodResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MethodResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MethodResponse
   * @throws IOException if the JSON string is invalid with respect to MethodResponse
   */
  public static MethodResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MethodResponse.class);
  }

  /**
   * Convert an instance of MethodResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

