/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * A reference to a unique stage identified in the format &lt;code&gt;{restApiId}/{stage}&lt;/code&gt;.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:10:54.869209+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class StageKey {
  public static final String SERIALIZED_NAME_REST_API_ID = "restApiId";
  @SerializedName(SERIALIZED_NAME_REST_API_ID)
  @javax.annotation.Nullable
  private String restApiId;

  public static final String SERIALIZED_NAME_STAGE_NAME = "stageName";
  @SerializedName(SERIALIZED_NAME_STAGE_NAME)
  @javax.annotation.Nullable
  private String stageName;

  public StageKey() {
  }

  public StageKey restApiId(@javax.annotation.Nullable String restApiId) {
    this.restApiId = restApiId;
    return this;
  }

  /**
   * Get restApiId
   * @return restApiId
   */
  @javax.annotation.Nullable
  public String getRestApiId() {
    return restApiId;
  }

  public void setRestApiId(@javax.annotation.Nullable String restApiId) {
    this.restApiId = restApiId;
  }


  public StageKey stageName(@javax.annotation.Nullable String stageName) {
    this.stageName = stageName;
    return this;
  }

  /**
   * Get stageName
   * @return stageName
   */
  @javax.annotation.Nullable
  public String getStageName() {
    return stageName;
  }

  public void setStageName(@javax.annotation.Nullable String stageName) {
    this.stageName = stageName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StageKey stageKey = (StageKey) o;
    return Objects.equals(this.restApiId, stageKey.restApiId) &&
        Objects.equals(this.stageName, stageKey.stageName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(restApiId, stageName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StageKey {\n");
    sb.append("    restApiId: ").append(toIndentedString(restApiId)).append("\n");
    sb.append("    stageName: ").append(toIndentedString(stageName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("restApiId");
    openapiFields.add("stageName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StageKey
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StageKey.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in StageKey is not found in the empty JSON string", StageKey.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StageKey.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `StageKey` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `restApiId`
      if (jsonObj.get("restApiId") != null && !jsonObj.get("restApiId").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("restApiId"));
      }
      // validate the optional field `stageName`
      if (jsonObj.get("stageName") != null && !jsonObj.get("stageName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("stageName"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StageKey.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StageKey' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StageKey> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StageKey.class));

       return (TypeAdapter<T>) new TypeAdapter<StageKey>() {
           @Override
           public void write(JsonWriter out, StageKey value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StageKey read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StageKey given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StageKey
   * @throws IOException if the JSON string is invalid with respect to StageKey
   */
  public static StageKey fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StageKey.class);
  }

  /**
   * Convert an instance of StageKey to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

