/*
 * Amazon API Gateway
 * <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
 *
 * The version of the OpenAPI document: 2015-07-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TestInvokeAuthorizerRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:10:54.869209+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class TestInvokeAuthorizerRequest {
  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  @javax.annotation.Nullable
  private Map<String, String> headers = new HashMap<>();

  public static final String SERIALIZED_NAME_MULTI_VALUE_HEADERS = "multiValueHeaders";
  @SerializedName(SERIALIZED_NAME_MULTI_VALUE_HEADERS)
  @javax.annotation.Nullable
  private Map<String, List<String>> multiValueHeaders = new HashMap<>();

  public static final String SERIALIZED_NAME_PATH_WITH_QUERY_STRING = "pathWithQueryString";
  @SerializedName(SERIALIZED_NAME_PATH_WITH_QUERY_STRING)
  @javax.annotation.Nullable
  private String pathWithQueryString;

  public static final String SERIALIZED_NAME_BODY = "body";
  @SerializedName(SERIALIZED_NAME_BODY)
  @javax.annotation.Nullable
  private String body;

  public static final String SERIALIZED_NAME_STAGE_VARIABLES = "stageVariables";
  @SerializedName(SERIALIZED_NAME_STAGE_VARIABLES)
  @javax.annotation.Nullable
  private Map<String, String> stageVariables = new HashMap<>();

  public static final String SERIALIZED_NAME_ADDITIONAL_CONTEXT = "additionalContext";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_CONTEXT)
  @javax.annotation.Nullable
  private Map<String, String> additionalContext = new HashMap<>();

  public TestInvokeAuthorizerRequest() {
  }

  public TestInvokeAuthorizerRequest headers(@javax.annotation.Nullable Map<String, String> headers) {
    this.headers = headers;
    return this;
  }

  public TestInvokeAuthorizerRequest putHeadersItem(String key, String headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

  /**
   * A key-value map of headers to simulate an incoming invocation request. This is where the incoming authorization token, or identity source, should be specified.
   * @return headers
   */
  @javax.annotation.Nullable
  public Map<String, String> getHeaders() {
    return headers;
  }

  public void setHeaders(@javax.annotation.Nullable Map<String, String> headers) {
    this.headers = headers;
  }


  public TestInvokeAuthorizerRequest multiValueHeaders(@javax.annotation.Nullable Map<String, List<String>> multiValueHeaders) {
    this.multiValueHeaders = multiValueHeaders;
    return this;
  }

  public TestInvokeAuthorizerRequest putMultiValueHeadersItem(String key, List<String> multiValueHeadersItem) {
    if (this.multiValueHeaders == null) {
      this.multiValueHeaders = new HashMap<>();
    }
    this.multiValueHeaders.put(key, multiValueHeadersItem);
    return this;
  }

  /**
   * The headers as a map from string to list of values to simulate an incoming invocation request. This is where the incoming authorization token, or identity source, may be specified.
   * @return multiValueHeaders
   */
  @javax.annotation.Nullable
  public Map<String, List<String>> getMultiValueHeaders() {
    return multiValueHeaders;
  }

  public void setMultiValueHeaders(@javax.annotation.Nullable Map<String, List<String>> multiValueHeaders) {
    this.multiValueHeaders = multiValueHeaders;
  }


  public TestInvokeAuthorizerRequest pathWithQueryString(@javax.annotation.Nullable String pathWithQueryString) {
    this.pathWithQueryString = pathWithQueryString;
    return this;
  }

  /**
   * The URI path, including query string, of the simulated invocation request. Use this to specify path parameters and query string parameters.
   * @return pathWithQueryString
   */
  @javax.annotation.Nullable
  public String getPathWithQueryString() {
    return pathWithQueryString;
  }

  public void setPathWithQueryString(@javax.annotation.Nullable String pathWithQueryString) {
    this.pathWithQueryString = pathWithQueryString;
  }


  public TestInvokeAuthorizerRequest body(@javax.annotation.Nullable String body) {
    this.body = body;
    return this;
  }

  /**
   * The simulated request body of an incoming invocation request.
   * @return body
   */
  @javax.annotation.Nullable
  public String getBody() {
    return body;
  }

  public void setBody(@javax.annotation.Nullable String body) {
    this.body = body;
  }


  public TestInvokeAuthorizerRequest stageVariables(@javax.annotation.Nullable Map<String, String> stageVariables) {
    this.stageVariables = stageVariables;
    return this;
  }

  public TestInvokeAuthorizerRequest putStageVariablesItem(String key, String stageVariablesItem) {
    if (this.stageVariables == null) {
      this.stageVariables = new HashMap<>();
    }
    this.stageVariables.put(key, stageVariablesItem);
    return this;
  }

  /**
   * A key-value map of stage variables to simulate an invocation on a deployed Stage.
   * @return stageVariables
   */
  @javax.annotation.Nullable
  public Map<String, String> getStageVariables() {
    return stageVariables;
  }

  public void setStageVariables(@javax.annotation.Nullable Map<String, String> stageVariables) {
    this.stageVariables = stageVariables;
  }


  public TestInvokeAuthorizerRequest additionalContext(@javax.annotation.Nullable Map<String, String> additionalContext) {
    this.additionalContext = additionalContext;
    return this;
  }

  public TestInvokeAuthorizerRequest putAdditionalContextItem(String key, String additionalContextItem) {
    if (this.additionalContext == null) {
      this.additionalContext = new HashMap<>();
    }
    this.additionalContext.put(key, additionalContextItem);
    return this;
  }

  /**
   * A key-value map of additional context variables.
   * @return additionalContext
   */
  @javax.annotation.Nullable
  public Map<String, String> getAdditionalContext() {
    return additionalContext;
  }

  public void setAdditionalContext(@javax.annotation.Nullable Map<String, String> additionalContext) {
    this.additionalContext = additionalContext;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestInvokeAuthorizerRequest testInvokeAuthorizerRequest = (TestInvokeAuthorizerRequest) o;
    return Objects.equals(this.headers, testInvokeAuthorizerRequest.headers) &&
        Objects.equals(this.multiValueHeaders, testInvokeAuthorizerRequest.multiValueHeaders) &&
        Objects.equals(this.pathWithQueryString, testInvokeAuthorizerRequest.pathWithQueryString) &&
        Objects.equals(this.body, testInvokeAuthorizerRequest.body) &&
        Objects.equals(this.stageVariables, testInvokeAuthorizerRequest.stageVariables) &&
        Objects.equals(this.additionalContext, testInvokeAuthorizerRequest.additionalContext);
  }

  @Override
  public int hashCode() {
    return Objects.hash(headers, multiValueHeaders, pathWithQueryString, body, stageVariables, additionalContext);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestInvokeAuthorizerRequest {\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    multiValueHeaders: ").append(toIndentedString(multiValueHeaders)).append("\n");
    sb.append("    pathWithQueryString: ").append(toIndentedString(pathWithQueryString)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    stageVariables: ").append(toIndentedString(stageVariables)).append("\n");
    sb.append("    additionalContext: ").append(toIndentedString(additionalContext)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("headers");
    openapiFields.add("multiValueHeaders");
    openapiFields.add("pathWithQueryString");
    openapiFields.add("body");
    openapiFields.add("stageVariables");
    openapiFields.add("additionalContext");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TestInvokeAuthorizerRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TestInvokeAuthorizerRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TestInvokeAuthorizerRequest is not found in the empty JSON string", TestInvokeAuthorizerRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TestInvokeAuthorizerRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TestInvokeAuthorizerRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("pathWithQueryString") != null && !jsonObj.get("pathWithQueryString").isJsonNull()) && !jsonObj.get("pathWithQueryString").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pathWithQueryString` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pathWithQueryString").toString()));
      }
      if ((jsonObj.get("body") != null && !jsonObj.get("body").isJsonNull()) && !jsonObj.get("body").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `body` to be a primitive type in the JSON string but got `%s`", jsonObj.get("body").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TestInvokeAuthorizerRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TestInvokeAuthorizerRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TestInvokeAuthorizerRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TestInvokeAuthorizerRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<TestInvokeAuthorizerRequest>() {
           @Override
           public void write(JsonWriter out, TestInvokeAuthorizerRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TestInvokeAuthorizerRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TestInvokeAuthorizerRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TestInvokeAuthorizerRequest
   * @throws IOException if the JSON string is invalid with respect to TestInvokeAuthorizerRequest
   */
  public static TestInvokeAuthorizerRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TestInvokeAuthorizerRequest.class);
  }

  /**
   * Convert an instance of TestInvokeAuthorizerRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

